### PR TITLE
add basic postgres testing setup

### PR DESCRIPTION
**Pull request by machow**
addresses #4. Note that right now...

* I'm not sure the right way to verify it works on travis. Maybe if you copy this to a branch in the repo?
* the calendar dates calculation is off, so the test fails, seeing "2012-12-31" but expecting "2013-01-01"

Happy to make any changes (or feel free to takeover)!

### CODE REVIEW

**Comment by machow** [comment]
Ah, it does run on travis! Updated so that tests work (except for the calendar date mismatch)

**Comment by ramnathv** [comment]
@machow The calendar date discrepancy is because sql `DATE_TRUNC` uses Monday as start of week vs. `floor_date` that defaults to Sunday. I have updated `generate_date_periods` to use Monday too. Can you rebase and push to see if the tests pass?

**Comment by machow** [comment]
Ah @ramnathv, I just noticed that `week_start` was added to the original test, but after I had copied it, so I need to add it to the copied test 😅. Hopefully this does it!

**Comment by machow** [comment]
@ramnathv I think this is ready to go! Do you want to adjust to your tastes and merge? For example, it has a docker-compose.yml, so that the db can be set up using `docker-compose up`, but feel free to remove if not useful :)

**Comment by ramnathv** [comment]
LGTM. Merging it in. Thanks 👍

**Pull request merged**
